//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkladEntities : DbContext
    {
        public SkladEntities()
            : base("name=SkladEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ведомость_прихода_на_склад> Ведомость_прихода_на_склад { get; set; }
        public virtual DbSet<Группа_контрагентов> Группа_контрагентов { get; set; }
        public virtual DbSet<Группа_товаров> Группа_товаров { get; set; }
        public virtual DbSet<Единицы_измерения> Единицы_измерения { get; set; }
        public virtual DbSet<Контрагент> Контрагент { get; set; }
        public virtual DbSet<Остатки> Остатки { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Техкарта> Техкарта { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
        public virtual DbSet<Цена> Цена { get; set; }
        public virtual DbSet<ТехЗадание> ТехЗадание { get; set; }
    }
}
