//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ведомость_прихода_на_склад
    {
        public Ведомость_прихода_на_склад()
        {

        }
        public Ведомость_прихода_на_склад(int id, DateTime date, int con, int sklad, int tovar, double kolvo, double summ)
        {
            Id = id;
            Дата = date;
            Контрагент = con;
            Склад = sklad;
            Количество = kolvo;
            Сумма = summ;
            Товар = tovar;
        }
        public int Id { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Контрагент { get; set; }
        public Nullable<bool> Проведено { get; set; }
        public Nullable<int> Склад { get; set; }
        public Nullable<double> Количество { get; set; }
        public Nullable<double> Сумма { get; set; }
        public Nullable<int> Товар { get; set; }
    
        public virtual Товар Товар1 { get; set; }
        public virtual Контрагент Контрагент1 { get; set; }
        public virtual Склад Склад1 { get; set; }
    }
}
