//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контрагент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Контрагент(int id, string Наименование, string Телефон, int Группа_контрагента, string Электронный_адрес, string Фактический_адрес)
        {
            Id = id;
            this.Наименование = Наименование;
            this.Телефон = Телефон;
            this.Группа_контрагента = Группа_контрагента;
            this.Электронный_адрес = Электронный_адрес;
            this.Фактический_адрес = Фактический_адрес;
        }
        public Контрагент()
        {
            this.Ведомость_прихода_на_склад = new HashSet<Ведомость_прихода_на_склад>();
        }
    
        public int Id { get; set; }
        public string Наименование { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> Группа_контрагента { get; set; }
        public string Электронный_адрес { get; set; }
        public string Фактический_адрес { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомость_прихода_на_склад> Ведомость_прихода_на_склад { get; set; }
        public virtual Группа_контрагентов Группа_контрагентов { get; set; }
    }
}
