//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public Пользователь() { }
        public Пользователь(int id, string login, string password, string surname, string name, string pyth, int dos) 
        {
            Id = id;
            Логин = login;
            Пароль = password;
            Право_доступа = dos;
            Фамилия = surname;
            Имя = name;
            Отчество = pyth;
        }
        public int Id { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> Право_доступа { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
    }
}
