//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склад
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Склад(int id, string Name, string Adress)
        {
            Id = id;
            Наименование = Name;
            Адрес = Adress;
        }
        public Склад()
        {
            this.Ведомость_прихода_на_склад = new HashSet<Ведомость_прихода_на_склад>();
            this.ТехЗадание = new HashSet<ТехЗадание>();
            this.ТехЗадание1 = new HashSet<ТехЗадание>();
        }
    
        public int Id { get; set; }
        public string Наименование { get; set; }
        public string Адрес { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомость_прихода_на_склад> Ведомость_прихода_на_склад { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТехЗадание> ТехЗадание { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТехЗадание> ТехЗадание1 { get; set; }
    }
}
