//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТехЗадание
    {
        public ТехЗадание() { }
        public ТехЗадание(int id, int Склад_материала, int Склад_для_продукции, int Объем_производства)
        {

        }
        public int Id { get; set; }
        public Nullable<int> Техкарта { get; set; }
        public Nullable<int> Склад_для_продукции { get; set; }
        public Nullable<double> Объем_производства { get; set; }
        public Nullable<int> Склад_материала { get; set; }
    
        public virtual Склад Склад { get; set; }
        public virtual Склад Склад1 { get; set; }
        public virtual Техкарта Техкарта1 { get; set; }
    }
}
