//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Техкарта
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Техкарта()
        {
            this.ТехЗадание = new HashSet<ТехЗадание>();
        }
        public Техкарта(int id, int mat, int продукция, double Затраты)
        {
            Id = id;
            Материал = mat;
            Готовая_продукция = продукция;
            Затраты_на_производство = Затраты;
        }
        public int Id { get; set; }
        public Nullable<double> Затраты_на_производство { get; set; }
        public Nullable<int> Готовая_продукция { get; set; }
        public Nullable<int> Материал { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТехЗадание> ТехЗадание { get; set; }
        public virtual Товар Товар { get; set; }
        public virtual Товар Товар1 { get; set; }
    }
}
