//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Ведомость_прихода_на_склад = new HashSet<Ведомость_прихода_на_склад>();
            this.Техкарта = new HashSet<Техкарта>();
            this.Техкарта1 = new HashSet<Техкарта>();
        }
    
        public int Id { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Единица_измерения { get; set; }
        public Nullable<int> Цена { get; set; }
        public string Артикул { get; set; }
        public Nullable<int> Группа_товара { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомость_прихода_на_склад> Ведомость_прихода_на_склад { get; set; }
        public virtual Группа_товаров Группа_товаров { get; set; }
        public virtual Единицы_измерения Единицы_измерения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Техкарта> Техкарта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Техкарта> Техкарта1 { get; set; }
        public virtual Цена Цена1 { get; set; }
    }
}
